name: 🚀 Build and Deploy (Next.js)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Setup Node.js 🟢
        uses: actions/setup-node@v5
        with:
          node-version: 24
          # cache: "npm"

      - name: Install dependencies 📦
        run: |
          npm install

      - name: Build static site 🔧
        env:
          NEXT_PUBLIC_GA_ID: ${{ vars.NEXT_PUBLIC_GA_ID }}
          NEXT_PUBLIC_THEME: ${{ vars.NEXT_PUBLIC_THEME }}
        run: |
          npm run build

      - name: Add .nojekyll 🩹
        run: echo "" > out/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
