name: 🚀 Build and Deploy (Next.js)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_GA_ID=${{ vars.NEXT_PUBLIC_GA_ID }}" >> .env
          echo "NEXT_PUBLIC_THEME=${{ vars.NEXT_PUBLIC_THEME }}" >> .env

      - name: Debug env
        run: |
          echo "Theme: ${{ vars.NEXT_PUBLIC_THEME }}"
          echo "GA: ${{ vars.NEXT_PUBLIC_GA_ID }}"

      - name: Install dependencies 📦
        run: |
          npm install

      - name: Build static site 🔧
        env:
          NEXT_PUBLIC_GA_ID: ${{ vars.NEXT_PUBLIC_GA_ID }}
          NEXT_PUBLIC_THEME: ${{ vars.NEXT_PUBLIC_THEME }}
        run: |
          npm run build

      - name: Add .nojekyll
        run: echo "" > out/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
